variable "public_key_path" {}
variable "private_key_path" {}
variable "image_name" {}
variable "ssh_user" {}
variable "number_of_bastions" {}
variable "flavor_bastion" {}
variable "floating_ip_bastion" {}
variable "number_of_workers" {}
variable "flavor_worker" {}
variable "network_name" {}
