- hosts: worker
  gather_facts: yes
  roles:
    - role: geerlingguy.java
      become: true

- hosts: bastion
  become: true
  tasks:
    - name: Install fail2ban
      apt:
        update_cache: yes
        name: fail2ban
        state: latest
