- hosts: worker
  gather_facts: yes
  become: true

  pre_tasks:
    - name: Update apt cache if required
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - role: geerlingguy.docker

- hosts: bastion
  become: true

  tasks:
    - name: Install fail2ban
      apt:
        update_cache: yes
        name: fail2ban
        state: latest
